### ISSUE TITLE
Localization not passed in to ResolveLink

### ISSUE THREAD

**Issue by tgfl-tom** [sdl/dxa-web-application-dotnet#13]
The localization parameter is not always passed into ResolveLink even when it is available.  

Our project utilises the DD4T REST provider, which requires that the publication/localization is available.

I have created a pull request (https://github.com/sdl/dxa-web-application-dotnet/pull/11) with a fix

**Comment by rpannekoek** [comment]
Sorry for the late response; we were quite busy with getting a DXA 1.3 release out lately.
Although I agree it makes sense to pass down a Localization object (just because we can), I was wondering: couldn't you use the Localization/Publication ID which is part of the TCM URI?

**Comment by rpannekoek** [comment]
Since DXA 2.0,  link resolving is largely done in the DXA Model Service.
The Link Resolver is still used for a few use cases:

- Link resolving in (static) site maps
- Language Selector (`PageController.Resolve`)

Adding a `Localization` parameter to the `ILinkResolver` interface would be a compatibility break. Since the Publication ID is available in the TCM URI (and thus a Localization object can be retrieved if really needed), this does not justify a compatibility break.
