### ISSUE TITLE
Ability to exclude XpmMetadata and XpmPropertyMetadata from ?format=json result

### ISSUE THREAD

**Issue by NunoLinhares** [sdl/dxa-web-application-dotnet#32]
I think the ?format=json "trick" is awesome for potential data integrations with either 3rd party tools or mobile apps.
This however returns all the data, including a significant amount of Experience Manager metadata which is irrelevant in most integration scenarios. It would be good to have the ability to exclude this info from the returned data - either through configuration, or ideally, by having an additional parameter specifying you _want_ the XPM data (so the default would be to _not_ include it).

Example: http://nuno-dxa.azurewebsites.net/?format=json

**Comment by bkoopman** [comment]
At current the `XpmPropertyMetadata`, `MvcData` and `XpmMetadata` objects are indeed not all that interesting for third party tools or mobile apps. The current json is a complete representation of the data in our model(s). While DXA currently is suitable for third party tools and mobile apps, it is not ideal for this, since it is rather on the heavy side (you need a web application just for the model mapping and are not using any of the view logic). It would be better to serve this model json from a model service, which could be optimized for delivering the data required for 3rd party tools/ mobile apps.

**Comment by rpannekoek** [comment]
TSI-1942 (internal issue ID for tracking purposes)

**Comment by bkoopman** [comment]
`XpmPropertyMetadata`, `MvcData` and `XpmMetadata` objects should only be available on staging site where XPM is enabled, they should never show on a live site, so reclassifying this as a defect

**Comment by rpannekoek** [comment]
Fixed in DXA 1.7.
