### ISSUE TITLE
Mapping issue with Embedded Schema in retrofit mode

### ISSUE THREAD

**Issue by justsayantan** [sdl/dxa-web-application-dotnet#40]
We are using DXA 1.7 for our project. As it is a migration project from Tridion Classic Implementation to DXA implementation. So we have to enable the retrofit mode. 
Using this we are facing error while trying to map embedded items in the model.  This is only working when the content model and embedded schema model is using same prefix. But if I change the prefix, then it is not working. I have tried all possible combination but not able to figure out any solution.

As a work around we are now using same prefix for content and embedded schema, but need a proper solution for that.

**Comment by rpannekoek** [comment]
This issue has been fixed in DXA 2.0 code base (there will be a DXA 2.0 CTP release soon), but only for the new "R2" model mapping.
This new model mapping (based on a new Data Model instead of the DD4T Data Model and using a new Model Service) will be the default in DXA 2.0.
For backwards compatibility and gradual migration purposes, DXA 2.0 also still supports "Legacy" model mapping, but we don't intend to fix existing bugs in there.

**Comment by rpannekoek** [comment]
Fixed in DXA 2.0 CTP 1 release.
