### ISSUE TITLE
Included Pages XMP Markup causes "Update Preview" loop

### ISSUE THREAD

**Issue by JaimeSA** [sdl/dxa-web-application-dotnet#9]
When a component in a included page is updated within the including page using XPM, and its respective page (included page) is not published afterwards, The "Update Sesssion Preview" button remains active and XPM asks for the update.

I think this has to do with the Component Presentations of the included pages not living withing the Including page itself, hence XPM cannot render the them with the latest version of either the component or component template

**Comment by bkoopman** [comment]
This is indeed a known side effect of the include pages being editable inside the actual page. Which is also why we added the edit icon on the include pages, so that you can click that and open the include page itself (making it fully editable), after which you can uatomatically get it publishe by pressing the Finish Editing button. And then you can easily go back to your original page with the back icon on the inlude page.

Since this issue is related to XPM behavior, I'm labeling it currently as won't fix, but I will make sure we discuss it as part of XPM and see if we can put better support for these scenarios in the product.
